/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 11
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_value = 1,
  sym_item_text = 2,
  sym_section = 3,
  sym_separator = 4,
  sym_fence_line = 5,
  sym_key_name = 6,
  sym_item_dash = 7,
  sym_text_line = 8,
  sym_document = 9,
  sym__lines = 10,
  sym__line = 11,
  sym_key_value = 12,
  sym_item = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_value] = "value",
  [sym_item_text] = "item_text",
  [sym_section] = "section",
  [sym_separator] = "separator",
  [sym_fence_line] = "fence_line",
  [sym_key_name] = "key_name",
  [sym_item_dash] = "item_dash",
  [sym_text_line] = "text_line",
  [sym_document] = "document",
  [sym__lines] = "_lines",
  [sym__line] = "_line",
  [sym_key_value] = "key_value",
  [sym_item] = "item",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_value] = sym_value,
  [sym_item_text] = sym_item_text,
  [sym_section] = sym_section,
  [sym_separator] = sym_separator,
  [sym_fence_line] = sym_fence_line,
  [sym_key_name] = sym_key_name,
  [sym_item_dash] = sym_item_dash,
  [sym_text_line] = sym_text_line,
  [sym_document] = sym_document,
  [sym__lines] = sym__lines,
  [sym__line] = sym__line,
  [sym_key_value] = sym_key_value,
  [sym_item] = sym_item,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_item_text] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_line] = {
    .visible = true,
    .named = true,
  },
  [sym_key_name] = {
    .visible = true,
    .named = true,
  },
  [sym_item_dash] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__lines] = {
    .visible = false,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
  [1] =
    {field_key, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(5);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_item_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_item_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 2, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 1, .external_lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_value] = ACTIONS(1),
    [sym_item_text] = ACTIONS(1),
    [sym_section] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym_fence_line] = ACTIONS(1),
    [sym_key_name] = ACTIONS(1),
    [sym_item_dash] = ACTIONS(1),
    [sym_text_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(8),
    [sym__lines] = STATE(9),
    [sym__line] = STATE(2),
    [sym_key_value] = STATE(2),
    [sym_item] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_section] = ACTIONS(5),
    [sym_separator] = ACTIONS(5),
    [sym_fence_line] = ACTIONS(5),
    [sym_key_name] = ACTIONS(7),
    [sym_item_dash] = ACTIONS(9),
    [sym_text_line] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__lines] = STATE(10),
    [sym__line] = STATE(2),
    [sym_key_value] = STATE(2),
    [sym_item] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_section] = ACTIONS(5),
    [sym_separator] = ACTIONS(5),
    [sym_fence_line] = ACTIONS(5),
    [sym_key_name] = ACTIONS(7),
    [sym_item_dash] = ACTIONS(9),
    [sym_text_line] = ACTIONS(5),
  },
  [STATE(3)] = {
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_value] = ACTIONS(15),
    [sym_section] = ACTIONS(13),
    [sym_separator] = ACTIONS(13),
    [sym_fence_line] = ACTIONS(13),
    [sym_key_name] = ACTIONS(13),
    [sym_item_dash] = ACTIONS(13),
    [sym_text_line] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(17), 7,
      sym_section,
      sym_separator,
      sym_fence_line,
      sym_key_name,
      sym_item_dash,
      sym_text_line,
      ts_builtin_sym_end,
  [10] = 1,
    ACTIONS(19), 7,
      sym_section,
      sym_separator,
      sym_fence_line,
      sym_key_name,
      sym_item_dash,
      sym_text_line,
      ts_builtin_sym_end,
  [20] = 1,
    ACTIONS(19), 7,
      sym_section,
      sym_separator,
      sym_fence_line,
      sym_key_name,
      sym_item_dash,
      sym_text_line,
      ts_builtin_sym_end,
  [30] = 3,
    ACTIONS(7), 1,
      sym_key_name,
    ACTIONS(21), 1,
      sym_item_text,
    STATE(6), 1,
      sym_key_value,
  [40] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [44] = 1,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
  [48] = 1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 10,
  [SMALL_STATE(6)] = 20,
  [SMALL_STATE(7)] = 30,
  [SMALL_STATE(8)] = 40,
  [SMALL_STATE(9)] = 44,
  [SMALL_STATE(10)] = 48,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lines, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 1, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 2, 0, 2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lines, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_section = 0,
  ts_external_token_separator = 1,
  ts_external_token_fence_line = 2,
  ts_external_token_key_name = 3,
  ts_external_token_item_dash = 4,
  ts_external_token_text_line = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_section] = sym_section,
  [ts_external_token_separator] = sym_separator,
  [ts_external_token_fence_line] = sym_fence_line,
  [ts_external_token_key_name] = sym_key_name,
  [ts_external_token_item_dash] = sym_item_dash,
  [ts_external_token_text_line] = sym_text_line,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_section] = true,
    [ts_external_token_separator] = true,
    [ts_external_token_fence_line] = true,
    [ts_external_token_key_name] = true,
    [ts_external_token_item_dash] = true,
    [ts_external_token_text_line] = true,
  },
  [2] = {
    [ts_external_token_key_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_promptdown_external_scanner_create(void);
void tree_sitter_promptdown_external_scanner_destroy(void *);
bool tree_sitter_promptdown_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_promptdown_external_scanner_serialize(void *, char *);
void tree_sitter_promptdown_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_promptdown(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_promptdown_external_scanner_create,
      tree_sitter_promptdown_external_scanner_destroy,
      tree_sitter_promptdown_external_scanner_scan,
      tree_sitter_promptdown_external_scanner_serialize,
      tree_sitter_promptdown_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "promptdown",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
